export const FIELD_LABELS: Record<string, string> = {
  name: "Nome",
  title: "Título",
  isActive: "Ativo",
  isFeatured: "Em destaque",
  subtitle: "Subtítulo",
  linkUrl: "URL do link",
  slug: "Slug",
  price: "Preço",
  durationLabel: "Duração",
  shortDescription: "Descrição curta",
  longDescription: "Descrição longa",
  imageBase64: "Imagem",
  newPassword: "Nova senha",
  firstName: "Nome",
  lastName: "Sobrenome",
  email: "Email",
  role: "Função",
  material: "Material",
  colors: "Cores",
  dimensions: "Dimensões",
  mainImageBase64: "Imagem principal",
  categoryId: "Categoria",
  isSale: "Promoção",
  salePrice: "Preço promocional",
};
